export const STORE_GAME_LIST = "g2a/STORE_GAME_LIST";
export const STORE_UPDATED_GAME_ITEM = "g2a/STORE_UPDATED_GAME_ITEM";

export const ACTION_FETCH_LISTINGS = "g2a/ACTION_FETCH_LISTINGS";

export const FETCH_LISTINGS_STARTED = "g2a/FETCH_LISTINGS_STARTED";
export const FETCH_LISTINGS_COMPLETED = "g2a/FETCH_LISTINGS_COMPLETED";
export const FETCH_LISTINGS_FAILED = "g2a/FETCH_LISTINGS_FAILED";

export const FETCH_AUCTION_LIST_STARTED = "g2a/FETCH_AUCTION_LIST_STARTED";
export const FETCH_AUCTION_LIST_COMPLETED = "g2a/FETCH_AUCTION_LIST_COMPLETED";
export const FETCH_AUCTION_LIST_FAILED = "g2a/FETCH_AUCTION_LIST_FAILED";

export const FETCH_AUCTION_STARTED = "g2a/FETCH_AUCTION_STARTED";
export const FETCH_AUCTION_COMPLETED = "g2a/FETCH_AUCTION_COMPLETED";
export const FETCH_AUCTION_FAILED = "g2a/FETCH_AUCTION_FAILED";

export const ACTION_TOGGLE_EXPAND = "g2a/ACTION_TOGGLE_EXPAND";

export const UPDATE_GAME_ITEM = "g2a/UPDATE_GAME_ITEM";

export const FETCH_UPDATED_GAME_ITEM = "g2a/FETCH_UPDATED_GAME_ITEM";

export const FETCH_SELECTED_AUCTION = "g2a/FETCH_SELECTED_AUCTION";
