export const ACTION_FETCH_PRICES = "steam/ACTION_FETCH_PRICES";

export const FETCH_PRICES_STARTED = "steam/FETCH_PRICES_STARTED";
export const FETCH_PRICES_COMPLETED = "steam/FETCH_PRICES_COMPLETED";
export const FETCH_PRICES_FAILED = "steam/FETCH_PRICES_FAILED";
